package: ylicense
version: '0.9.6'
author: Yakamara Media GmbH & Co. KG
supportpage: https://github.com/yakamara/ylicense

page:
    title: 'translate:title'
    perm: admin[]
    subpages:
        main:
            title: 'translate:main'
            icon: rex-icon fa-list
        table:
            title: 'translate:astable'
            icon: rex-icon fa-table
        addons:
            title: 'translate:addons'
            icon: rex-icon fa-table
        config:
            title: 'translate:config'
            icon: rex-icon fa-wrench
requires:
    redaxo: '^5.12'
    php:
        version: '>=7.4'

console_commands:
    ylicense:list: list_short
    ylicense:list-full: list_full
